###CI/CD CODE


name: 🚀 Auto Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: 📡 Connect to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/Profile
            git pull origin main

            cd backend
            if [ ! -d "venv" ]; then
              python -m venv venv
            fi
            source venv/Scripts/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput

            cd ../frontend
            npm install
            npm run build

            echo "✅ Deployment complete."
